/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang 15.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "src/adder.v:1.1-8.10" *)
module adder(a, b, s);
  wire _00_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _01_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [3:0] _03_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _04_;
  (* force_downto = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [5:0] _05_;
  (* src = "src/adder.v:2.14-2.15" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "src/adder.v:3.14-3.15" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "src/adder.v:4.10-4.11" *)
  output s;
  wire s;
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'hefffffffffffffff)
  ) _06_ (
    .I0(_05_[0]),
    .I1(_05_[1]),
    .I2(_05_[2]),
    .I3(_05_[3]),
    .I4(_05_[4]),
    .I5(_05_[5]),
    .O(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _07_ (
    .I0(_04_[0]),
    .I1(_04_[1]),
    .O(_05_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41" *)
  LUT6 #(
    .INIT(64'h0000000000000001)
  ) _08_ (
    .I0(_02_[0]),
    .I1(_02_[1]),
    .I2(_02_[2]),
    .I3(_02_[3]),
    .I4(_02_[4]),
    .I5(_02_[5]),
    .O(_05_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) _09_ (
    .I0(_01_[0]),
    .I1(_01_[1]),
    .O(_05_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/opt/homebrew/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'h0001)
  ) _10_ (
    .I0(_03_[0]),
    .I1(_03_[1]),
    .I2(_03_[2]),
    .I3(_03_[3]),
    .O(_05_[3])
  );
  (* keep = 32'd1 *)
  IBUF _11_ (
    .I(a[0]),
    .O(_02_[0])
  );
  (* keep = 32'd1 *)
  IBUF _12_ (
    .I(a[1]),
    .O(_03_[0])
  );
  (* keep = 32'd1 *)
  IBUF _13_ (
    .I(a[2]),
    .O(_04_[0])
  );
  (* keep = 32'd1 *)
  IBUF _14_ (
    .I(a[3]),
    .O(_02_[1])
  );
  (* keep = 32'd1 *)
  IBUF _15_ (
    .I(a[4]),
    .O(_03_[1])
  );
  (* keep = 32'd1 *)
  IBUF _16_ (
    .I(a[5]),
    .O(_01_[0])
  );
  (* keep = 32'd1 *)
  IBUF _17_ (
    .I(a[6]),
    .O(_05_[0])
  );
  (* keep = 32'd1 *)
  IBUF _18_ (
    .I(a[7]),
    .O(_03_[2])
  );
  (* keep = 32'd1 *)
  IBUF _19_ (
    .I(b[0]),
    .O(_05_[1])
  );
  (* keep = 32'd1 *)
  IBUF _20_ (
    .I(b[1]),
    .O(_02_[2])
  );
  (* keep = 32'd1 *)
  IBUF _21_ (
    .I(b[2]),
    .O(_02_[3])
  );
  (* keep = 32'd1 *)
  IBUF _22_ (
    .I(b[3]),
    .O(_01_[1])
  );
  (* keep = 32'd1 *)
  IBUF _23_ (
    .I(b[4]),
    .O(_02_[4])
  );
  (* keep = 32'd1 *)
  IBUF _24_ (
    .I(b[5]),
    .O(_04_[1])
  );
  (* keep = 32'd1 *)
  IBUF _25_ (
    .I(b[6]),
    .O(_03_[3])
  );
  (* keep = 32'd1 *)
  IBUF _26_ (
    .I(b[7]),
    .O(_02_[5])
  );
  (* keep = 32'd1 *)
  OBUF _27_ (
    .I(_00_),
    .O(s)
  );
endmodule
