all:
	cd adder && make
	cd arm_core && make
	cd test_args && make
	#cd vexriscv && make
	cd jpeg && make
	cd black_parrot && make

clean:
	cd adder && make clean
	cd arm_core && make clean
	cd test_args && make clean
	cd vexriscv && make clean
	cd jpeg && make clean
	cd black_parrot && make clean
