YOSYS ?= yosys
EQY ?= eqy
VERILATOR ?= verilator
NAJA_EDIT ?= $(NAJA_INSTALL)/bin/naja_edit
PRIMITIVES ?= $(NAJA_INSTALL)/shared/primitives
SET_PYTHONPATH ?= $(NAJA_INSTALL)/lib/python
SCRIPTS ?= ../../scripts
