all:
	cd arm_core && make
	#cd vexriscv && make
	cd jpeg && make
	cd black_parrot && make
	cd megaboom && make

clean:
	cd arm_core && make clean
	cd vexriscv && make clean
	cd jpeg && make clean
	cd black_parrot && make clean
	cd megaboom && make clean
